/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package planestudios;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("hello gradle");
    	return true;
    }
}
